### ISSUE TITLE
Update README with clarifications on the setup process

### ISSUE THREAD

**Issue by santiagocabrera96** [VirtusLab/graphbuddy#14]
When trying to use GraphBuddy I had two problems with the installation:
    
  - The scala version (2.12.8) was not supported; therefore, sbt couldn't find the package,
  - The Intellij plugin complained about connecting to localhost:9000, looks like the plugin didn't work in my Intellij version (2019.3)

Could you please include in the README to make sure the project scala version is supported iby looking at https://dl.bintray.com/virtuslab/graphbuddy/com/virtuslab/semanticgraphs/, and that If there's an error connecting to localhost:9000 check for Intellij updates.

**Comment by liosedhel** [comment]
Hello @santiagocabrera96,
Sorry for the late answer (somehow I missed your issue). 

Graph Buddy scalac plugin supports following scala versions:

- 2.13.3
- 2.13.2
- 2.13.1
- 2.12.12
- 2.12.11
- 2.11.12

This info can be found also here: https://bintray.com/virtuslab/graphbuddy/scalac-plugin/0.2.8. 
I updated also the Readme - thanks for the suggestion.
If missing support for 2.12.8 scala is a blocker for you - let me know, I will try to publish new artefact with scala 2.12.8 included.

The newest Graph Buddy 0.4.0 does not require a local server anymore indeed. All the information about project configuration can be found here: https://graphbuddy.virtuslab.com/#installing-and-configuring-the-extension. For technical reasons (introducing by Jetbrains JCEF support which makes the plugin way more usable) we support Intellij from 2020.2 onwards only. 

Hope you will find this useful, let me know if I can be of any help.
Krzysztof

**Comment by liosedhel** [comment]
Hello

Just to let you all know, scala 2.12.8 is now supported with semantic-graphs plugin 0.2.9. Currently supported Scala versions:

- 2.13.4
- 2.13.3
- 2.13.2
- 2.13.1
- 2.12.12
- 2.12.11
- 2.12.10
- 2.12.9
- 2.12.8
- 2.11.12

cheers,
Krzysztof
