### ISSUE TITLE
sbt-plugin is not available on Maven Central for Scala 2.13 as of 0.2.15

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/graphbuddy#21]
https://repo1.maven.org/maven2/org/virtuslab/semanticgraphs/ ->

![image](https://user-images.githubusercontent.com/3383210/152858692-57f1a7c8-64ad-4920-944c-1c455e7d965e.png)

**Comment by liosedhel** [comment]
sbt for version 0.13 uses scala 2.10. sbt for version > 1.0 uses scala 2.12 and was not migrated yet to a newer version. All should be good as scala-plugin is released for all different scala versions.  just add `addSbtPlugin("org.virtuslab.semanticgraphs" % "sbt-plugin" % "0.2.16")` to `project/plugins.sbt` :)

**Comment by PawelLipski** [comment]
Yeah, that was just a matter of myself putting the `*.sbt` file in top-level folder and not in `project/` 😛
