### ISSUE TITLE
scalac-plugin for Scala 2.13.8 would be useful

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/graphbuddy#22]
...so that I can test on my commercial project!

**Comment by liosedhel** [comment]
It's now ready
```
addCompilerPlugin("org.virtuslab.semanticgraphs" % "scalac-plugin" % "0.2.16" cross CrossVersion.full)
scalacOptions += "-Yrangepos"
```
I just need to adjust sbt plugin :)

**Comment by liosedhel** [comment]
sbt plugin is addjusted now as well :) you can try it out with `addSbtPlugin("org.virtuslab.semanticgraphs" % "sbt-plugin" % "0.2.15")`
